Repository etternagame/etterna, pull requests merged in 2019-11, with the labels that each got.

#640 Windows CrashHandler: Create a thread for separate stack
  src/archutils/Win32/Crash.cpp
Labels: Platform: Windows, Priority: Low, Type: Bug

#619 Add song BPM check in NotesLoaderSSC
  src/Etterna/Models/NoteLoaders/NotesLoaderSSC.cpp
Labels: Good First Issue, Priority: Low, Type: Bug

#604 Various tiny fixes and improvements (see within)
  Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/tags.lua
  Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
  Themes/Til Death/BGAnimations/_PlayerInfo.lua
  Themes/Til Death/BGAnimations/_chartpreview.lua
  Themes/Til Death/BGAnimations/_chorddensitygraph.lua
  Themes/Til Death/BGAnimations/_cursor.lua
  Themes/Til Death/Graphics/Player judgment/default.lua
  Themes/Til Death/Scripts/02 Branches.lua
  Themes/Til Death/Scripts/10 Widgets.lua
  Themes/Til Death/metrics.ini
  Themes/_fallback/BGAnimations/ScreenChatOverlay overlay.lua
  Themes/_fallback/Scripts/00 Utility.lua
  Themes/_fallback/Scripts/02 Branches.lua
  Themes/_fallback/Scripts/10 WifeSundries.lua
  Themes/_fallback/metrics.ini
  src/Etterna/Actor/Base/Actor.cpp
  src/Etterna/Actor/Base/Actor.h
  src/Etterna/Screen/Options/ScreenOptionsMasterPrefs.cpp
  src/Etterna/Singletons/PrefsManager.cpp
  src/Etterna/Singletons/PrefsManager.h
  src/RageUtil/Misc/RageMath.cpp
  src/RageUtil/Misc/RageMath.h
  src/arch/InputHandler/InputHandler_DirectInput.cpp
Labels: Priority: Low, Type: Maintenance

#652 Re-add Git Hash & Version Info Variables
  .changelog/Release_0-67.md
  CMake/Helpers/CMakeLinux.cmake
  CMakeLists.txt
  Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/other.lua
  src/Etterna/Globals/StepMania.cpp
  src/Etterna/Singletons/CommandLineActions.cpp
  src/Etterna/Singletons/LuaManager.cpp
  src/Etterna/verstub.in.cpp
  src/archutils/Unix/CrashHandlerChild.cpp
  src/archutils/Win32/CrashHandlerChild.cpp
  src/ver.h
Labels: Priority: Medium, Type: Bug, Type: Enhancement

#654 Rewrite RageUtil's ssprintf to Fix Occasional Stack Overflow Crash
  src/RageUtil/Utils/RageUtil.cpp
  src/RageUtil/Utils/RageUtil.h
Labels: Priority: Medium, Type: Bug, Type: Maintenance
