Repository etternagame/etterna, pull requests merged in 2019-05, with the labels that each got.

#513 Update README.md
  CMake/CPack/Windows/etterna_arrow.svg
  Docs/Building.md
  Docs/BuildingUpgrade.md
  Docs/Contributing.md
  Docs/images/etterna-logo-dark.svg
  Docs/images/etterna-logo-light.svg
  Docs/images/etterna-welcome.png
  LICENSE
  README.md
Labels: Priority: Low, Type: Enhancement

#532 CPack Hotfix - Install Directory
  CMake/Helpers/CPackSetup.cmake
Labels: Platform: Windows, Priority: Very Low, Type: Maintenance

#522 Rewrite Changelog to be Comprehensive & Updated
  .changelog/Release_0-01.md
  .changelog/Release_0-02.md
  .changelog/Release_0-03.md
  .changelog/Release_0-50.md
  .changelog/Release_0-51.md
  .changelog/Release_0-52.md
  .changelog/Release_0-53-0.md
  .changelog/Release_0-53-1.md
  .changelog/Release_0-54-0-pre1.md
  .changelog/Release_0-54-0-pre2.md
  .changelog/Release_0-54-0.md
  .changelog/Release_0-54-1-pre1.md
  .changelog/Release_0-54-1.md
  .changelog/Release_0-54-2.md
  .changelog/Release_0-55-0.md
  .changelog/Release_0-55-1.md
  .changelog/Release_0-55-2.md
  .changelog/Release_0-55-3.md
  .changelog/Release_0-56-0.md
  .changelog/Release_0-56-1.md
  .changelog/Release_0-56-2-pre1.md
  .changelog/Release_0-56-2.md
  .changelog/Release_0-57-0.md
  .changelog/Release_0-57-1.md
  .changelog/Release_0-60.md
  .changelog/Release_0-61-0.md
  .changelog/Release_0-61-1.md
  .changelog/Release_0-62-0.md
  .changelog/Release_0-62-1.md
  .changelog/Release_0-63.md
  .changelog/Release_0-64.md
  .changelog/Release_0-65-0.md
  .changelog/Release_0-65-1.md
  CHANGELOG.md
Labels: Priority: Very Low, Type: Maintenance
