Repository etternagame/etterna, pull requests merged in 2019-12, with the labels that each got.

#658 Fix Mac Travis Builds
  .travis.yml
Labels: Help Wanted, Platform: Mac, Priority: Low

#660 Change Windows CPack to use the old directory & generate the old shortcut
  .changelog/Release_0-67.md
  CMake/Helpers/CPackSetup.cmake
Labels: Platform: Windows, Priority: Low, Type: Enhancement

#663 Add exit tip to ScreenTestInput
  Themes/_fallback/BGAnimations/ScreenTestInput underlay.lua
  Themes/_fallback/Languages/en.ini
Labels: Language: Lua, Priority: Low, Type: Maintenance

#668 Remove Autosync Tempo & Manual Tempo Adjustments
  src/Etterna/Models/Misc/AdjustSync.cpp
  src/Etterna/Models/Misc/AdjustSync.h
  src/Etterna/Models/Songs/SongOptions.cpp
  src/Etterna/Models/Songs/SongOptions.h
  src/Etterna/Screen/Gameplay/ScreenGameplay.cpp
  src/Etterna/Screen/Others/ScreenDebugOverlay.cpp
  src/Etterna/Screen/Others/ScreenSyncOverlay.cpp
Labels: Priority: Low, Type: Maintenance

#667 Hotfix 0.67.1
  .changelog/Release_0-67-0.md
  .changelog/Release_0-67-1.md
  Assets/Toasties/legacy/default.lua
  CMake/CPack/Windows/ProductInfo.inc
  CMakeLists.txt
  Data/splash.png
  Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
  Themes/Til Death/BGAnimations/ScreenGameplay toasty/default.lua
  Themes/Til Death/BGAnimations/ScreenPlayerOptions overlay.lua
  Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/wifeTwirl.lua
  Themes/Til Death/BGAnimations/ScreenSelectMusic overlay/currentsort.lua
  Themes/Til Death/BGAnimations/ScreenSelectMusic overlay/default.lua
  Themes/Til Death/BGAnimations/offsetplot.lua
  Themes/_fallback/BGAnimations/ScreenPlayerOptions overlay.lua
  Themes/_fallback/Graphics/Common splash.png
  Themes/_fallback/Scripts/09 SimNSkinPreview.lua
  src/Etterna/Actor/Menus/MusicWheel.cpp
  src/Etterna/Actor/Menus/MusicWheel.h
  src/Etterna/Models/Misc/AdjustSync.cpp
  src/Etterna/Screen/Gameplay/ScreenGameplay.cpp
  src/Etterna/Screen/Gameplay/ScreenGameplaySyncMachine.cpp
  src/Etterna/Screen/Others/ScreenEvaluation.cpp
  src/Etterna/Singletons/GameManager.cpp
  src/Etterna/Singletons/GameState.h
  src/RageUtil/Graphics/RageDisplay.cpp
Labels: Priority: Medium, Type: Maintenance
