Repository etternagame/etterna, pull requests merged in 2019-06, with the labels that each got.

#538 Add Asset Picker
  Assets/Judgements/Judgment Normal 2x6.png
  Assets/Judgements/default 1x6.png
  Assets/Toasties/default/default.ogg
  Assets/Toasties/default/default.png
  Assets/Toasties/legacy/legacy.ogg
  Assets/Toasties/legacy/legacy.png
  Themes/Til Death/BGAnimations/ScreenAssetSettings overlay.lua
  Themes/Til Death/BGAnimations/ScreenAssetSettings underlay.lua
  Themes/Til Death/BGAnimations/ScreenGameplay toasty/default.lua
  Themes/Til Death/BGAnimations/ScreenNetRoom decorations/profile.lua
  Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/profile.lua
  Themes/Til Death/Graphics/Player judgment/default.lua
  Themes/Til Death/Languages/en.ini
  Themes/Til Death/metrics.ini
  Themes/_fallback/Scripts/11 AssetsConfig.lua
  Themes/_fallback/Scripts/12 AssetsUtils.lua
Labels: Language: Lua, Priority: Medium, Type: Enhancement

#559 Fix unassigned variable on linux
  CMake/Helpers/CPackSetup.cmake
Labels: Platform: Linux, Priority: High, Type: Bug

#561 Modify CMake order of operations
  CMakeLists.txt
Labels: Platform: Linux, Priority: Medium, Type: Bug, Type: Maintenance

#565 Update Building.md to include generator window
  Docs/Building.md
  Docs/images/cmake-gui-03.png
Labels: Priority: Very Low, Type: Enhancement
