Repository etternagame/etterna, pull requests merged in 2020-08, with the labels that each got.

#865 Fix some more nuanced errors related to RageTexture
  src/Etterna/Actor/Base/ActorFrameTexture.cpp
  src/Etterna/Actor/Base/ActorFrameTexture.h
  src/Etterna/Actor/Base/ActorMultiVertex.cpp
  src/Etterna/Actor/Base/ActorMultiVertex.h
  src/Etterna/Actor/Base/ModelTypes.cpp
  src/Etterna/Actor/Base/ModelTypes.h
  src/Etterna/Actor/Base/Sprite.cpp
  src/Etterna/Actor/Base/Sprite.h
  src/Etterna/Actor/Gameplay/NoteDisplay.cpp
  src/Etterna/Actor/Menus/GraphDisplay.cpp
  src/Etterna/Models/Fonts/Font.h
  src/Etterna/Models/Misc/ImageCache.cpp
  src/Etterna/Models/Songs/Song.cpp
  src/Etterna/Singletons/PrefsManager.cpp
  src/RageUtil/Graphics/RageBitmapTexture.cpp
  src/RageUtil/Graphics/RageDisplay_OGL.cpp
  src/RageUtil/Graphics/RageDisplay_OGL.h
  src/RageUtil/Graphics/RageTextureID.h
  src/RageUtil/Graphics/RageTextureManager.cpp
  src/RageUtil/Graphics/RageTextureManager.h
  src/arch/MovieTexture/MovieTexture.cpp
  src/arch/MovieTexture/MovieTexture.h
  src/arch/MovieTexture/MovieTexture_FFMpeg.cpp
  src/arch/MovieTexture/MovieTexture_FFMpeg.h
  src/arch/MovieTexture/MovieTexture_Generic.cpp
  src/arch/MovieTexture/MovieTexture_Generic.h
  src/arch/MovieTexture/MovieTexture_Null.cpp
  src/arch/MovieTexture/MovieTexture_Null.h
Labels: Priority: Medium, Type: Maintenance

#868 Fix muFFT-related issue stopping compilation on MSVC Debug Target
  src/RageUtil/Sound/RageSound.h
Labels: Platform: Windows

#873 Remove the unused crypto extern folder
  extern/crypto/CryptBn.cpp
  extern/crypto/CryptBn.h
  extern/crypto/CryptMD5.cpp
  extern/crypto/CryptMD5.h
  extern/crypto/CryptNoise.cpp
  extern/crypto/CryptPrime.cpp
  extern/crypto/CryptPrime.h
  extern/crypto/CryptRSA.cpp
  extern/crypto/CryptRSA.h
  extern/crypto/CryptRand.cpp
  extern/crypto/CryptRand.h
  extern/crypto/CryptSH512.cpp
  extern/crypto/CryptSH512.h
  extern/crypto/CryptSHA.cpp
  extern/crypto/CryptSHA.h
Labels: Priority: Very Low, Type: Maintenance

#883 Refactor MinaCalc's Chisel function to improve performance
  src/Etterna/MinaCalc/MinaCalc.cpp
Labels: Priority: Medium, Type: Maintenance
