Repository etternagame/etterna, pull requests merged in 2020-01, with the labels that each got.

#687 Make Win32 Invalid Parameter Handler more informative
  src/arch/ArchHooks/ArchHooks_Win32.cpp
Labels: Platform: Windows, Type: Maintenance

#677 Added X11 event handling to handle delete window event
  src/arch/LowLevelWindow/LowLevelWindow_X11.cpp
  src/arch/LowLevelWindow/LowLevelWindow_X11.h
Labels: Platform: Linux

#688 Iterate version to 0.68.0
  CMake/CPack/Windows/ProductInfo.inc
  CMakeLists.txt
  Data/splash.png
  Themes/_fallback/Graphics/Common splash.png
  src/Etterna/Singletons/GameState.h
Labels: Priority: Very Low, Type: Maintenance

#681 Improve RageUtil's vssprintf on Win32
  src/RageUtil/Utils/RageUtil.cpp
Labels: Platform: Windows, Priority: Low, Type: Maintenance
