Repository etternagame/etterna, pull requests merged in 2020-12, with the labels that each got.

#896 Update README.md to include MacOS installation procedure
  README.md
Labels: Platform: Mac, Type: Maintenance

#897 Tidy up building docs a bit, add arch dependencies
  Docs/Building.md
Labels: Platform: Linux, Type: Maintenance

#923 Add new feature request issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Priority: Low, Type: Maintenance

#901 Update Fedora dependencies libssl-devel -> openssl-static
  Docs/Building.md
Labels: Platform: Linux, Type: Maintenance
