Repository etternagame/etterna, pull requests merged in 2020-10, with the labels that each got.

#903 MinaCalc Profilemancy
  src/Etterna/MinaCalc/MinaCalc.cpp
  src/Etterna/MinaCalc/UlbuAcolytes.h
Labels: Priority: Medium, Type: Maintenance

#905 Add virtual default destructor to Core::ILogger so child destructors …
  src/Core/Services/ILogger.hpp
Labels: Priority: Low, Type: Maintenance

#911 🧾 Better AppInfo Organization
  CMake/CPack/Windows/ProductInfo.inc
  src/Core/CMakeLists.txt
  src/Core/Misc/AppInfo.hpp
  src/Core/Misc/AppInfo.in.cpp
  src/Etterna/CMakeLists.txt
  src/Etterna/Globals/StepMania.cpp
  src/Etterna/Singletons/CommandLineActions.cpp
  src/Etterna/Singletons/LuaManager.cpp
  src/Etterna/verstub.in.cpp
  src/archutils/Unix/CrashHandlerChild.cpp
  src/archutils/Win32/CrashHandlerChild.cpp
  src/ver.h
Labels: Priority: Low, Type: Enhancement, Type: Maintenance

#915 Fix issue #914
  src/RageUtil/Graphics/RageDisplay_OGL.cpp
Labels: Priority: Low, Type: Bug

#913 Unsolicited proof-of-concept machine learning jackspeed PR
  src/Etterna/MinaCalc/Dependent/HD_Sequencers/GenericSequencing.h
  src/Etterna/MinaCalc/MinaCalc.cpp
  src/Etterna/MinaCalc/PatternModHelpers.h
  src/Etterna/MinaCalc/UlbuAcolytes.h
Labels: Priority: Medium, Type: Enhancement
