Repository etternagame/etterna, pull requests merged in 2020-02, with the labels that each got.

#695 Rewrite interface for Color Editing
  Themes/Til Death/BGAnimations/ScreenColorEdit overlay.lua
  Themes/Til Death/Graphics/_thick circle (doubleres).png
  Themes/Til Death/Graphics/color_hsv.png
  Themes/Til Death/Graphics/color_sat_overlay.png
  Themes/Til Death/Languages/en.ini
  Themes/Til Death/Scripts/01 color_config.lua
  Themes/Til Death/metrics.ini
Labels: Language: Lua, Type: Enhancement

#697 Implement Borderless Fullscreen & Replace DisplayResolutions with DisplaySpec
  CMake/Helpers/CMakeLinux.cmake
  CMake/Modules/FindXinerama.cmake
  Themes/Til Death/BGAnimations/_cursor.lua
  Themes/_fallback/Languages/en.ini
  Themes/_fallback/Scripts/02 Utilities.lua
  Themes/_fallback/Scripts/03 DisplaySpecs.lua
  Themes/_fallback/metrics.ini
  src/Etterna/Actor/Menus/OptionRow.cpp
  src/Etterna/Globals/StepMania.cpp
  src/Etterna/Models/CMakeLists.txt
  src/Etterna/Models/Misc/DisplayResolutions.h
  src/Etterna/Models/Misc/DisplaySpec.cpp
  src/Etterna/Models/Misc/DisplaySpec.h
  src/Etterna/Models/Misc/OptionRowHandler.cpp
  src/Etterna/Models/Misc/OptionRowHandler.h
  src/Etterna/Screen/Options/ScreenOptionsMasterPrefs.cpp
  src/Etterna/Screen/Options/ScreenOptionsMasterPrefs.h
  src/Etterna/Singletons/PrefsManager.cpp
  src/Etterna/Singletons/PrefsManager.h
  src/RageUtil/Graphics/RageDisplay.cpp
  src/RageUtil/Graphics/RageDisplay.h
  src/RageUtil/Graphics/RageDisplay_D3D.cpp
  src/RageUtil/Graphics/RageDisplay_D3D.h
  src/RageUtil/Graphics/RageDisplay_Null.cpp
  src/RageUtil/Graphics/RageDisplay_Null.h
  src/RageUtil/Graphics/RageDisplay_OGL.cpp
  src/RageUtil/Graphics/RageDisplay_OGL.h
  src/arch/LowLevelWindow/LowLevelWindow.h
  src/arch/LowLevelWindow/LowLevelWindow_MacOSX.h
  src/arch/LowLevelWindow/LowLevelWindow_MacOSX.mm
  src/arch/LowLevelWindow/LowLevelWindow_Win32.cpp
  src/arch/LowLevelWindow/LowLevelWindow_Win32.h
  src/arch/LowLevelWindow/LowLevelWindow_X11.cpp
  src/arch/LowLevelWindow/LowLevelWindow_X11.h
  src/archutils/Unix/X11Helper.cpp
  src/archutils/Unix/X11Helper.h
  src/archutils/Win32/GraphicsWindow.cpp
  src/archutils/Win32/GraphicsWindow.h
Labels: Type: Enhancement, Type: Maintenance

#674 Update default judgment textures
  Assets/Judgments/Judgment Normal 2x6 (Doubleres).png
  Assets/Judgments/Judgment Normal 2x6.png
  Assets/Judgments/default 1x6 (Doubleres).png
  Assets/Judgments/default 1x6.png
  Themes/_fallback/Scripts/11 AssetsConfig.lua
Labels: Language: Lua, Type: Maintenance

#684 Fix some broken fallback theme Lua
  Themes/_fallback/BGAnimations/ScreenSystemLayer overlay/default.lua
  Themes/_fallback/Graphics/Player judgment/default.lua
  Themes/_fallback/metrics.ini
Labels: Language: Lua, Priority: Low, Type: Maintenance

#698 Add new upper Grade Tiers, Preference for SSRNorm Prioritizing, and the Quint
  Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
  Themes/Til Death/BGAnimations/ScreenEvaluation decorations/scoreboard.lua
  Themes/Til Death/BGAnimations/ScreenSelectMusic decorations/songsearch.lua
  Themes/Til Death/Languages/en.ini
  Themes/Til Death/Languages/zh.ini
  Themes/Til Death/Scripts/01 color_config.lua
  Themes/Til Death/Scripts/02 Colors.lua
  Themes/_fallback/Languages/en.ini
  Themes/_fallback/Scripts/10 Scores.lua
  Themes/_fallback/Scripts/10 Texts.lua
  Themes/_fallback/metrics.ini
  src/Etterna/Models/Misc/DBProfile.cpp
  src/Etterna/Models/Misc/Grade.cpp
  src/Etterna/Models/Misc/Grade.h
  src/Etterna/Models/Misc/HighScore.cpp
  src/Etterna/Models/Misc/PlayerStageStats.cpp
  src/Etterna/Screen/Options/ScreenOptionsMasterPrefs.cpp
  src/Etterna/Singletons/DownloadManager.cpp
  src/Etterna/Singletons/PrefsManager.cpp
  src/Etterna/Singletons/PrefsManager.h
Labels: Priority: Very Low, Type: Enhancement

#680 Update macOS dependencies and build instructions.
  Docs/Building.md
Labels: Platform: Mac, Priority: Low, Type: Maintenance

#705 Uncomment Win32 GraphicsWindow DisplaySpec Validation
  src/archutils/Win32/GraphicsWindow.cpp
Labels: Platform: Windows, Priority: Low

#704 Hotfix 0.68.1
  .changelog/Release_0-68-0.md
  .changelog/Release_0-68-1.md
  CHANGELOG.md
  CMake/CPack/Windows/ProductInfo.inc
  CMakeLists.txt
  Data/splash.png
  Themes/Til Death/BGAnimations/ScreenEvaluation decorations/default.lua
  Themes/Til Death/BGAnimations/ScreenEvaluation decorations/scoreboard.lua
  Themes/Til Death/BGAnimations/ScreenGameplay overlay/WifeJudgmentSpotting.lua
  Themes/Til Death/BGAnimations/ScreenGameplay overlay/messagebox.lua
  Themes/Til Death/BGAnimations/ScreenSelectMusic overlay/default.lua
  Themes/Til Death/BGAnimations/offsetplot.lua
  Themes/Til Death/Graphics/ComboGraphP2 MaxCombo.lua
  Themes/Til Death/Graphics/GradeDisplayEval Failed.lua
  Themes/Til Death/Graphics/GradeDisplayEval Tier01.lua
  Themes/Til Death/Graphics/GradeDisplayEval Tier02.lua
  Themes/Til Death/Graphics/GradeDisplayEval Tier03.lua
  Themes/Til Death/Graphics/GradeDisplayEval Tier04.lua
  Themes/Til Death/Graphics/GradeDisplayEval Tier05.lua
  Themes/Til Death/Graphics/GradeDisplayEval Tier06.lua
  Themes/Til Death/Graphics/GradeDisplayEval Tier07.lua
  Themes/Til Death/Graphics/GradeDisplayEval Tier08.lua
  Themes/Til Death/Scripts/02 CustomizeGameplay.lua
  Themes/_fallback/Graphics/Common splash.png
  Themes/_fallback/Languages/de.ini
  Themes/_fallback/Languages/en.ini
  Themes/_fallback/Languages/es.ini
  Themes/_fallback/Languages/fr.ini
  Themes/_fallback/Languages/ja.ini
  Themes/_fallback/Languages/nl.ini
  Themes/_fallback/Languages/pl.ini
  Themes/_fallback/Languages/zh.ini
  Themes/_fallback/base._ini
  Themes/_fallback/metrics.ini
  src/Etterna/Models/Misc/HighScore.cpp
  src/Etterna/Models/Misc/PlayerStageStats.cpp
  src/Etterna/Screen/Others/ScreenEvaluation.cpp
  src/Etterna/Singletons/GameState.h
  src/Etterna/Singletons/ScoreManager.cpp
  src/RageUtil/Graphics/RageDisplay.cpp
  src/archutils/Win32/GraphicsWindow.cpp
  src/archutils/Win32/GraphicsWindow.h
Labels: Priority: Medium, Type: Maintenance
