Repository etternagame/etterna, pull requests merged in 2021-07, with the labels that each got.

#1001 🔑 macOS Auto-Untranslocation
  src/Core/Misc/PlogLogger.cpp
  src/Core/Platform/PlatformMac.mm
Labels: Platform: Mac, Priority: Medium, Type: Enhancement

#1009 Mount /rootfs so linux audio drivers work
  src/Etterna/Globals/StepMania.cpp
Labels: Platform: Linux, Priority: Medium

#998 Show number of played songs per pack in song wheel
  Themes/_fallback/Languages/en.ini
  Themes/_fallback/metrics.ini
  src/Etterna/Actor/Menus/MusicWheelItem.cpp
  src/Etterna/Screen/Options/ScreenOptionsMasterPrefs.cpp
  src/Etterna/Singletons/PrefsManager.cpp
  src/Etterna/Singletons/PrefsManager.h
  src/RageUtil/Misc/RageTypes.cpp
  src/RageUtil/Misc/RageTypes.h
Labels: Priority: Very Low, Type: Enhancement
